# Generated by Django 5.0.4 on 2024-04-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyCommentSerializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=255)),
                ('Reply_comment', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'reply_comments',
            },
        ),
    ]
