# Generated by Django 5.0.4 on 2024-04-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='likes',
            table='likes',
        ),
    ]
