# Generated by Django 5.0.4 on 2024-04-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=2, upload_to='gallery_images/'),
            preserve_default=False,
        ),
    ]
