# Generated by Django 5.0.4 on 2024-04-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
